name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Base Project & Add Dependencies
        run: |
          cd ..
          flutter create --org com.mylivestream streamapp
          cd streamapp
          flutter pub add zego_uikit_prebuilt_live_streaming
          cp -f ../my-live-app/lib/main.dart lib/main.dart
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk ../my-live-app/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: live-stream-app
          path: app-release.apk
          
          
